name: 'Tender Form'
multiple: FALSE
category: 'Appel Offres'
enabled: TRUE
fields:
  webform:
    type: webform_decoupled
    label: 'Formulaire'
    options:
      '#required': TRUE
      '#default_value':
        webform_id: vactory_tender_form
extra_fields:
  title:
    type: text
    label: "Titre"
  intro:
    type: text_format
    label: 'Introduction'
    options:
      '#format': 'full_html'
