name: "Animated Slider"
category: "Animated DFs"
multiple: true
enabled: TRUE
fields:
  bigImage:
    type: image
    label: "Big image"
    options:
      "#required": TRUE
  smallImage:
    type: image
    label: "Small image"
    options:
      "#required": TRUE
  title:
    type: text
    label: "Card title"
    options:
      "#required": TRUE
  content:
    type: textarea
    label: "Card content"
    options:
      "#required": TRUE
  link:
    type: url_extended
    label: "Link"
