name: "Tab Images"
multiple: TRUE
limit: 4
category: "Animated DFs"
enabled: TRUE
fields:
  image:
    type: image
    label: "Image"
    options:
      "#required": TRUE
  title:
    type: text
    label: "Title"
    options:
      "#required": TRUE
  content:
    type: text
    label: "Content"
    options:
      "#format": full_html
      "#required": TRUE
  link:
    type: url_extended
    label: "Link"
