name: "Timeline - V3"
multiple: true
category: "Animated DFs"
enabled: TRUE
fields:
  image:
    type: image
    label: "image"
    options:
      "#required": TRUE
  date:
    type: text
    label: "date"
    options:
      "#required": TRUE
  content:
    type: textarea
    label: "Content"
    options:
      "#required": TRUE
  link:
    type: url_extended
    label: "link"
extra_fields:
  title:
    type: text
    label: "Title"
    options:
      "#required": TRUE
  content:
    type: "textarea"
    label: "Content"
  cta:
    type: url_extended
    label: "Call to action"

